//! Textos del receptor que ve el usuario: (clave, español, inglés). El
//! idioma activo lo pone `i18n`; `tr!("clave")` devuelve el texto y
//! `tr!("clave", a, b)` rellena `{0}`, `{1}`. Un test comprueba que toda
//! clave usada existe, que ninguna sobra y que los huecos coinciden.

pub const TABLE: &[(&str, &str, &str)] = &[
    // --- RetroArch
    ("retroarch.why_portable", "portable, junto al ejecutable", "portable, next to the executable"),
    ("retroarch.why_roaming", "configuración de usuario", "user configuration"),
    ("retroarch.why_flatpak", "Flatpak", "Flatpak"),
    ("retroarch.why_snap", "Snap", "Snap"),
    ("retroarch.why_manual", "carpeta elegida", "selected folder"),
    ("retroarch.not_found", "No encuentro retroarch.cfg. Abre RetroArch una vez o elige su carpeta en Ajustes.", "retroarch.cfg not found. Open RetroArch once or select its folder in Settings."),
    ("retroarch.error", "RetroArch: {0}", "RetroArch: {0}"),
    ("retroarch.already", "RetroArch ya estaba configurado:", "RetroArch was already set up:"),
    ("retroarch.open", "RetroArch está abierto. Cierra RetroArch para activar el mando en red; se configurará al cerrarse.", "RetroArch is open. Close RetroArch to enable the network gamepad; setup will run on close."),
    ("retroarch.phone_open", "Cierra RetroArch para activar el mando en red", "Close RetroArch to enable the network gamepad"),
    ("retroarch.configured_after_close", "RetroArch configurado al cerrarse. Ya puedes abrirlo:", "RetroArch set up on close. You can open it now:"),
    ("retroarch.configured", "RetroArch configurado:", "RetroArch set up:"),
    ("retroarch.phone_configured", "RetroArch listo. Ábrelo y juega.", "RetroArch is ready. Open it and play."),
    ("retroarch.restore_open", "Cierra RetroArch para restaurar su configuración. Se restaurará al cerrarse.", "Close RetroArch to restore its configuration. It will be restored on close."),
    ("retroarch.restored", "retroarch.cfg restaurado. Autoconfiguración de RetroArch desactivada.", "retroarch.cfg restored. Automatic RetroArch setup is off."),
    ("retroarch.nothing_restore", "No hay nada de PepoMote que restaurar en retroarch.cfg. Autoconfiguración de RetroArch desactivada.", "Nothing from PepoMote to restore in retroarch.cfg. Automatic RetroArch setup is off."),
    ("retroarch.found", "RetroArch encontrado: {0}", "RetroArch found: {0}"),
    ("retroarch.keyboard_unavailable", "Pon la ventana de RetroArch en primer plano para escribir (y activa el foco de juego si el juego usa teclado).", "Bring the RetroArch window to the front to type (and enable game focus if the game uses a keyboard)."),
    ("retroarch.osd_ready", "PepoMote: mando del movil conectado", "PepoMote: phone controller connected"),
    ("win.mode_retroarch", "Modo RetroArch: todos juegan", "RetroArch mode: everyone plays"),
    ("win.retroarch_live", "RetroArch {0} responde · {1} · {2} sondeos/s", "RetroArch {0} is responding · {1} · {2} polls/s"),
    ("win.retroarch_live_short", "RetroArch {0} responde · {1} sondeos/s", "RetroArch {0} is responding · {1} polls/s"),
    ("win.retroarch_playing", "jugando {0} ({1})", "playing {0} ({1})"),
    ("win.retroarch_paused", "en pausa: {0} ({1})", "paused: {0} ({1})"),
    ("win.retroarch_menu", "en el menú", "in the menu"),
    ("win.retroarch_degraded", "RetroArch está abierto pero no responde a los comandos de red: mando en modo degradado. Activa Ajustes → Red → Comandos de red y reinícialo, o pulsa Configurar RetroArch con RetroArch cerrado.", "RetroArch is open but does not answer network commands: controller in degraded mode. Enable Settings → Network → Network Commands and restart it, or press Set up RetroArch with RetroArch closed."),
    ("win.retroarch_waiting", "Esperando a RetroArch (ábrelo con el mando en red activado)", "Waiting for RetroArch (open it with the network gamepad enabled)"),
    ("win.configure_retroarch", "Configurar RetroArch", "Set up RetroArch"),
    ("win.restore_retroarch", "Restaurar mi retroarch.cfg", "Restore my retroarch.cfg"),
    ("win.retroarch_help", "Cada móvil es un jugador: RetroPad de dos sticks, mando de NES (Mando Wii de lado) o pistola de luz (apunta el Jugador 1). Con RetroArch cerrado, PepoMote activa el mando en red y los comandos de red en retroarch.cfg; Home abre el menú de RetroArch y la cabecera del móvil trae guardar/cargar estado, avance rápido y rebobinar. El receptor lee el historial de RetroArch al cargar un juego y el móvil enseña el mando de esa consola. Restaurar deshace esas claves y desactiva la autoconfiguración.", "Each phone is a player: a two-stick RetroPad, a NES pad (sideways Wii Remote) or a light gun (Player 1 points). With RetroArch closed, PepoMote enables the network gamepad and network commands in retroarch.cfg; Home opens the RetroArch menu and the phone header brings save/load state, fast-forward and rewind. The receiver reads RetroArch's history when a game loads and the phone shows that console's pad. Restore undoes those keys and turns automatic setup off."),
    ("cfg.auto_retroarch", "Configurar RetroArch automáticamente (modo RetroArch)", "Set up RetroArch automatically (RetroArch mode)"),
    ("cfg.retroarch_folder", "Carpeta de RetroArch", "RetroArch folder"),
    ("cfg.retroarch_folder_help", "Carpeta del ejecutable o la que contiene retroarch.cfg (o el propio archivo). Se detecta al abrir RetroArch; Detectar busca la versión de Steam.", "Executable folder or the folder containing retroarch.cfg (or the file itself). Detected when RetroArch opens; Detect looks for the Steam version."),
    ("win.badge_nunchuk_retroarch", "Nunchuk · sin uso en RetroArch", "Nunchuk · unused in RetroArch"),
    ("win.badge_retropad", "J{0} · RetroPad", "P{0} · RetroPad"),
    ("win.badge_retro_console", "J{0} · {1}", "P{0} · {1}"),
    ("win.retroarch_game", "Último juego cargado: {0} · {1} ({2}): el móvil enseña ese mando", "Last loaded game: {0} · {1} ({2}): the phone shows that pad"),
    ("win.retroarch_game_generic", "Último juego cargado: {0} ({1}) · consola sin plantilla: RetroPad", "Last loaded game: {0} ({1}) · no console template: RetroPad"),
    ("win.badge_retro_nes", "J{0} · Mando NES", "P{0} · NES pad"),
    ("win.badge_retro_gun", "J{0} · Pistola", "P{0} · Light gun"),
    ("auto.retroarch_opened", "RetroArch abierto: modo RetroArch", "RetroArch opened: RetroArch mode"),
    ("auto.retroarch_closed", "RetroArch cerrado: modo puntero", "RetroArch closed: pointer mode"),
    ("auto.retroarch_closed_dolphin", "RetroArch cerrado: modo Dolphin (Dolphin sigue abierto)", "RetroArch closed: Dolphin mode (Dolphin is still open)"),
    ("auto.retroarch_closed_cemu", "RetroArch cerrado: modo Wii U (Cemu sigue abierto)", "RetroArch closed: Wii U mode (Cemu is still open)"),
    ("auto.retroarch_closed_eden", "RetroArch cerrado: modo Switch (Eden sigue abierto)", "RetroArch closed: Switch mode (Eden is still open)"),
    ("auto.dolphin_closed_retroarch", "Dolphin cerrado: modo RetroArch (RetroArch sigue abierto)", "Dolphin closed: RetroArch mode (RetroArch is still open)"),
    ("auto.cemu_closed_retroarch", "Cemu cerrado: modo RetroArch (RetroArch sigue abierto)", "Cemu closed: RetroArch mode (RetroArch is still open)"),
    ("auto.eden_closed_retroarch", "Eden cerrado: modo RetroArch (RetroArch sigue abierto)", "Eden closed: RetroArch mode (RetroArch is still open)"),
    ("tray.mode_retroarch", "RetroArch", "RetroArch"),
    // --- Switch
    ("eden.servers_full", "Eden ya tiene ocho servidores DSU. Libera uno en su configuración de movimiento y vuelve a intentarlo.", "Eden already has eight DSU servers. Remove one in its motion settings and try again."),
    ("eden.kind_pro","Pro Controller","Pro Controller"),
    ("eden.player_kind","J{0} {1}","P{0} {1}"),
    ("eden.why_portable","portable","portable"),
    ("eden.why_roaming","configuración de usuario","user configuration"),
    ("eden.why_manual","carpeta elegida","selected folder"),
    ("eden.not_found","No encuentro Eden. Ábrelo una vez o elige su carpeta en Ajustes.","Eden not found. Open it once or select its folder in Settings."),
    ("eden.open","Eden está abierto. Cierra Eden para aplicar estos mandos; se configurará al cerrarse.","Eden is open. Close Eden to apply these controllers; setup will run on close."),
    ("eden.phone_open","Cierra Eden para aplicar los mandos de Switch","Close Eden to apply the Switch controllers"),
    ("eden.configured_after_close","Eden configurado al cerrarse. Ya puedes abrirlo:","Eden set up on close. You can open it now:"),
    ("eden.configured","Eden configurado:","Eden set up:"),
    ("eden.phone_configured","Switch listo. Abre Eden y juega.","Switch is ready. Open Eden and play."),
    ("eden.error","Eden: {0}","Eden: {0}"),
    ("eden.restore_open","Cierra Eden para restaurar tus mandos. Se restaurarán al cerrarse.","Close Eden to restore your controllers. They will be restored on close."),
    ("eden.restored","Mandos de Eden restaurados. Autoconfiguración de Switch desactivada.","Eden controllers restored. Automatic Switch setup is off."),
    ("eden.nothing_restore","No hay mandos de PepoMote que restaurar. Autoconfiguración de Switch desactivada.","No PepoMote controllers to restore. Automatic Switch setup is off."),
    ("eden.found","Eden encontrado: {0}","Eden found: {0}"),
    ("eden.keyboard_unavailable","Abre el teclado de Eden y pon su ventana en primer plano para escribir.","Open the keyboard in Eden and bring its window to the front to type."),
    ("win.switch_clients","Switch: {0} cliente(s) DSU","Switch: {0} DSU client(s)"),
    ("win.configure_eden","Configurar Eden","Set up Eden"),
    ("win.restore_eden","Restaurar mis mandos de Eden","Restore my Eden controllers"),
    ("win.switch_help","Cada móvil es un Pro Controller. Con Eden cerrado, PepoMote configura botones, sticks y movimiento. Cambia el reparto con Eden cerrado. Restaurar recupera tus mandos y desactiva la autoconfiguración.","Each phone is a Pro Controller. With Eden closed, PepoMote sets up buttons, sticks and motion. Change the player layout with Eden closed. Restore recovers your controllers and turns automatic setup off."),
    ("cfg.auto_eden","Configurar Eden automáticamente (modo Switch)","Set up Eden automatically (Switch mode)"),
    ("cfg.eden_folder","Carpeta de Eden","Eden folder"),
    ("cfg.eden_folder_help","Carpeta del ejecutable o la que contiene qt-config.ini. Se detecta al abrir Eden.","Executable folder or the folder containing qt-config.ini. Detected when Eden opens."),
    ("win.badge_nunchuk_switch","Nunchuk · sin uso en Switch","Nunchuk · unused in Switch"),
    ("win.badge_switch_pro","J{0} · Pro Controller","P{0} · Pro Controller"),
    ("auto.eden_opened","Eden abierto: modo Switch","Eden opened: Switch mode"),
    ("auto.eden_closed","Eden cerrado: modo puntero","Eden closed: pointer mode"),
    ("auto.eden_closed_dolphin","Eden cerrado: modo Dolphin (Dolphin sigue abierto)","Eden closed: Dolphin mode (Dolphin is still open)"),
    ("auto.eden_closed_cemu","Eden cerrado: modo Wii U (Cemu sigue abierto)","Eden closed: Wii U mode (Cemu is still open)"),
    ("auto.dolphin_closed_eden","Dolphin cerrado: modo Switch (Eden sigue abierto)","Dolphin closed: Switch mode (Eden is still open)"),
    ("auto.cemu_closed_eden","Cemu cerrado: modo Switch (Eden sigue abierto)","Cemu closed: Switch mode (Eden is still open)"),
    // --- ventana
    ("win.tagline", "Apunta. Haz clic. Juega.", "Point. Click. Play."),
    ("win.waiting", "Esperando al móvil…", "Waiting for the phone…"),
    ("win.another_player", "¿Otro jugador? Escanea", "Another player? Scan"),
    ("win.footer", "v{0} · pv1 · Inyección: {1}", "v{0} · pv1 · Injection: {1}"),
    ("win.inj_none", "ninguna", "none"),
    ("win.lang_switch", "Cambiar a {0}", "Switch to {0}"),
    ("win.no_camera_code", "Sin cámara: código", "No camera: code"),
    ("win.dolphin_clients", "Dolphin: {0} cliente(s) DSU", "Dolphin: {0} DSU client(s)"),
    ("win.configure_dolphin", "Configurar Dolphin", "Set up Dolphin"),
    (
        "win.dolphin_help",
        "¿Dolphin enseña el mando desconectado? Modo Dolphin en el móvil, juego de Wii, y reinicia Dolphin; la carpeta configurada tiene que ser la suya (en Dolphin: Archivo, «Abrir carpeta de usuario»).",
        "Does Dolphin show the controller disconnected? Dolphin mode on the phone, a Wii game, and restart Dolphin; the configured folder must be Dolphin's own (in Dolphin: File, “Open User Folder”).",
    ),
    ("win.cemu_clients", "Cemu (Wii U): {0} cliente(s) DSU", "Cemu (Wii U): {0} DSU client(s)"),
    ("win.configure_cemu", "Configurar Cemu", "Set up Cemu"),
    (
        "win.cemu_help",
        "Con Cemu cerrado. Jugador 1 = GamePad (y ve la pantalla del GamePad en el móvil), los demás Pro Controller; «Mando de Wii» se elige en el móvil.",
        "With Cemu closed. Player 1 = GamePad (and sees the GamePad screen on the phone), the rest Pro Controller; “Wii Remote” is chosen on the phone.",
    ),
    ("win.mode_pointer", "Modo puntero (apunta el Jugador 1)", "Pointer mode (Player 1 points)"),
    ("win.mode_dolphin", "Modo Dolphin: todos juegan", "Dolphin mode: everyone plays"),
    ("win.mode_cemu", "Modo Wii U (Cemu): todos juegan", "Wii U mode (Cemu): everyone plays"),
    ("win.mode_switch", "Modo Switch: todos juegan", "Switch mode: everyone plays"),
    ("win.pps", "{0} paquetes/s · sensor {1} Hz", "{0} packets/s · sensor {1} Hz"),
    ("win.tilt", "inclinación", "tilt"),
    (
        "win.tilt_tip",
        "Este móvil apunta por inclinación (sin giroscopio real): inclínalo a los lados para mover el cursor en horizontal y arriba/abajo para la vertical. Se elige en los Ajustes del móvil.",
        "This phone points by tilting (no real gyroscope): tilt it sideways to move the cursor horizontally and up/down for vertical. Selected in the phone's Settings.",
    ),
    ("win.heartbeat_tip", "Latido del Jugador 1: {0} ms ahora (últimos {1} latidos)", "Player 1 heartbeat: {0} ms now (last {1} beats)"),
    ("win.badge_nunchuk_unused", "J{0} · Nunchuk (sin uso: J{0} no es Mando Wii)", "P{0} · Nunchuk (unused: P{0} is not a Wii Remote)"),
    ("win.badge_nunchuk", "J{0} · Nunchuk", "P{0} · Nunchuk"),
    ("win.badge_nunchuk_spare", "J{0} · Nunchuk (sin uso: J{0} ya lleva Nunchuk)", "P{0} · Nunchuk (unused: P{0} already has a Nunchuk)"),
    ("win.badge_player_nunchuk", "J{0} · Mando + Nunchuk", "P{0} · Wii Remote + Nunchuk"),
    ("win.badge_gamepad", "J{0} · GamePad", "P{0} · GamePad"),
    ("win.badge_screen_only", "J{0} · pantalla del GamePad", "P{0} · GamePad screen"),
    ("win.badge_pro", "J{0} · Pro", "P{0} · Pro"),
    ("win.badge_wiimote", "J{0} · Mando Wii", "P{0} · Wii Remote"),
    ("win.badge_player", "J{0}", "P{0}"),
    // --- reparación (Linux)
    (
        "fix.uinput_missing",
        "El módulo uinput no está cargado (no existe /dev/uinput): sin él no puedo mover el cursor.",
        "The uinput module is not loaded (/dev/uinput does not exist): without it I cannot move the cursor.",
    ),
    ("fix.uinput_denied", "Sin permiso para mover el cursor (/dev/uinput).", "No permission to move the cursor (/dev/uinput)."),
    ("fix.applying", "Aplicando… responde al diálogo de contraseña", "Applying… answer the password dialog"),
    ("fix.retry", "🔧 Reintentar", "🔧 Retry"),
    ("fix.now", "🔧 Reparar ahora", "🔧 Fix now"),
    ("fix.dialog_once", "Un diálogo del sistema pedirá tu contraseña una sola vez", "A system dialog will ask for your password just once"),
    (
        "fix.manual_no_dialog",
        "Si el diálogo no aparece (sesión sin agente de polkit), pega esto en un terminal:",
        "If the dialog does not appear (session without a polkit agent), paste this in a terminal:",
    ),
    (
        "fix.manual_no_pkexec",
        "No hay pkexec en este sistema. Pega esto en un terminal (pide tu contraseña una vez):",
        "There is no pkexec on this system. Paste this in a terminal (it asks for your password once):",
    ),
    ("fix.copy_cmd", "Copiar comando", "Copy command"),
    ("fix.copied", "Copiado", "Copied"),
    (
        "fix.relogin",
        "Si después sigue sin permiso, cierra sesión y vuelve a entrar (la regla se aplica al iniciar sesión).",
        "If it still has no permission afterwards, log out and back in (the rule applies at login).",
    ),
    (
        "fix.no_auth",
        "No se pudo autenticar: en esta sesión no hay agente de polkit (nadie puede pedir la contraseña) o la contraseña no era válida",
        "Could not authenticate: this session has no polkit agent (nobody can ask for the password) or the password was not valid",
    ),
    ("fix.polkit_silent", "polkit no responde: {0}", "polkit is not responding: {0}"),
    ("fix.exit_code", "código {0}", "code {0}"),
    ("fix.signal", "terminado por una señal", "killed by a signal"),
    ("fix.failed", "Reparación fallida: {0}", "Repair failed: {0}"),
    ("fix.title", "Configuración del sistema pendiente", "System setup pending"),
    (
        "fix.explain_dialog",
        "Un diálogo del sistema («Se requiere autenticación para ejecutar /bin/sh como superusuario») pedirá tu contraseña de administrador: es PepoMote aplicando esto una sola vez: la regla udev y el módulo uinput para mover el cursor, y el puerto {0} (y mDNS) en el firewall.",
        "A system dialog (“Authentication is required to run /bin/sh as the super user”) will ask for your admin password: that is PepoMote applying this once: the udev rule and uinput module to move the cursor, and port {0} (and mDNS) in the firewall.",
    ),
    ("fix.auto_in", "Se abrirá solo en {0} s", "It opens by itself in {0} s"),
    ("fix.not_now", "Ahora no", "Not now"),
    ("fix.done_both", "Listo: cursor y firewall configurados", "Done: cursor and firewall set up"),
    ("fix.done_uinput", "Listo: cursor configurado (no hay firewall activo)", "Done: cursor set up (no firewall active)"),
    ("fix.done_partial", "Aplicado en parte: {0}", "Partly applied: {0}"),
    ("fix.sec_uinput_ok", "cursor configurado", "cursor set up"),
    ("fix.sec_uinput_no_module", "este kernel no trae el módulo uinput", "this kernel has no uinput module"),
    ("fix.sec_firewall_ok", "firewall abierto ({0})", "firewall opened ({0})"),
    ("fix.sec_firewall_none", "sin firewall activo", "no firewall active"),
    ("fix.sec_error", "{0}: {1}", "{0}: {1}"),
    ("fix.manual_firewall", "Para abrir el firewall a mano:", "To open the firewall by hand:"),
    ("fix.ok_dismiss", "Vale", "OK"),
    // --- firewall (Linux)
    (
        "fw.blocked",
        "El firewall ({0}) está bloqueando el puerto {1} del móvil.",
        "The firewall ({0}) is blocking the phone's port {1}.",
    ),
    (
        "fw.unknown",
        "{0} está activo y no puedo leer sus reglas: si el móvil no conecta, el puerto {1} está cerrado.",
        "{0} is on and its rules cannot be read: if the phone cannot connect, port {1} is closed.",
    ),
    // --- la ventana no abre (Linux): último recurso, por notificación de escritorio
    ("ui.start_failed_title", "PepoMote no ha podido abrir su ventana", "PepoMote could not open its window"),
    (
        "ui.start_failed_body",
        "Detalles en {0}. Ejecuta «PepoMote --diag» y pega el informe en un issue. Prueba a lanzarlo con LIBGL_ALWAYS_SOFTWARE=1 o PEPOMOTE_UI_BACKEND=x11.",
        "Details in {0}. Run “PepoMote --diag” and paste the report in an issue. Try launching it with LIBGL_ALWAYS_SOFTWARE=1 or PEPOMOTE_UI_BACKEND=x11.",
    ),
    ("fix.no_pkexec_launch", "No pude lanzar pkexec: {0}", "Could not launch pkexec: {0}"),
    // --- ajustes
    ("cfg.title", "Ajustes", "Settings"),
    ("cfg.sensitivity", "Sensibilidad", "Sensitivity"),
    ("cfg.sens_help", "Grados de giro para cruzar la pantalla (menos = más rápido)", "Degrees of turn to cross the screen (less = faster)"),
    ("cfg.abs", "Apuntado absoluto", "Absolute pointing"),
    (
        "cfg.abs_help",
        "Activado: el cursor está donde apunta el móvil, y vuelve al mismo sitio si vuelves a apuntar igual (la altura la fija la gravedad; el giro, el último recentrado). El recorrido es exacto: Windows no le aplica su aceleración de ratón.\n\nDesactivado (relativo): como un ratón, solo cuentan los desplazamientos, con la aceleración del sistema si la tienes activada. Es el modo para juegos que capturan el ratón.\n\nEn movimiento los dos son idénticos (1:1 con el giroscopio). La diana (mantenerla) recentra en los dos, también en el mando apaisado.\n\nUn móvil sin giroscopio real apunta por inclinación (a los lados y arriba/abajo): los dos modos valen igual, con el mismo ajuste de sensibilidad.",
        "On: the cursor is where the phone points, and it returns to the same spot if you point the same way again (height comes from gravity; turn, from the last recenter). The travel is exact: Windows applies no mouse acceleration to it.\n\nOff (relative): like a mouse, only the movement counts, with the system acceleration if you have it on. This is the mode for games that capture the mouse.\n\nWhile moving both are identical (1:1 with the gyroscope). The target button (hold it) recenters in both, on the sideways controller too.\n\nA phone without a real gyroscope points by tilting (sideways and up/down): both modes work the same, with the same sensitivity setting.",
    ),
    ("cfg.auto_dolphin", "Configurar Dolphin automáticamente (multijugador)", "Set up Dolphin automatically (multiplayer)"),
    ("cfg.auto_cemu", "Configurar Cemu automáticamente (modo Wii U)", "Set up Cemu automatically (Wii U mode)"),
    ("cfg.auto_mode", "Cambiar de modo automáticamente con el emulador", "Switch mode automatically with the emulator"),
    (
        "cfg.auto_mode_help",
        "Al abrir Dolphin, Cemu o Eden, el receptor y los móviles pasan al modo correspondiente. Al cerrarlo conservan el modo elegido, salvo que actives «Volver al puntero al cerrar un emulador».\n\nDesactiva este ajuste para cambiar de modo siempre a mano.",
        "Opening Dolphin, Cemu or Eden switches the receiver and phones to its mode. Closing it keeps the selected mode unless you enable Return to pointer when an emulator closes.\n\nTurn this setting off to always select modes manually.",
    ),
    ("cfg.return_to_pointer", "Volver al puntero al cerrar un emulador", "Return to pointer when an emulator closes"),
    ("cfg.return_to_pointer_help",
        "Desactivado: al cerrar Dolphin, Cemu o Eden, PepoMote se queda en el modo elegido.\n\nActivado: al cerrar el emulador del modo activo, vuelve al puntero; si queda otro emulador abierto, pasa a su modo. Requiere el cambio de modo automático.",
        "Off: closing Dolphin, Cemu or Eden leaves PepoMote in the selected mode.\n\nOn: closing the active emulator returns to pointer mode; if another emulator is still open, it switches to that mode. Requires automatic mode switching."),
    ("cfg.cemu_folder", "Carpeta de Cemu", "Cemu folder"),
    ("cfg.auto_hint", "automática", "automatic"),
    ("cfg.detect", "Detectar", "Detect"),
    (
        "cfg.cemu_folder_help",
        "Solo hace falta si Cemu está en un sitio raro; se aprende sola al verlo abierto.",
        "Only needed if Cemu lives somewhere unusual; it is learned by itself when Cemu is seen open.",
    ),
    ("cfg.dolphin_folder", "Carpeta de Dolphin", "Dolphin folder"),
    (
        "cfg.dolphin_folder_help",
        "La del Dolphin.exe. Un Dolphin portable (RetroBat, LaunchBox…) guarda su configuración ahí; se aprende sola al verlo abierto.",
        "The one with Dolphin.exe. A portable Dolphin (RetroBat, LaunchBox…) keeps its configuration there; it is learned by itself when Dolphin is seen open.",
    ),
    ("cfg.pointing_on", "Apuntado absoluto en", "Absolute pointing on"),
    ("cfg.all_screens", "Todas las pantallas", "All screens"),
    ("cfg.only_screen", "Solo {0} ({1}×{2})", "Only {0} ({1}×{2})"),
    (
        "cfg.screens_help",
        "Todas = el cursor llega a los tres monitores. Una sola = apuntado preciso para jugar.",
        "All = the cursor reaches every monitor. One = precise pointing for games.",
    ),
    ("cfg.theme", "Tema", "Theme"),
    ("cfg.theme_system", "Como el sistema", "Like the system"),
    ("cfg.theme_light", "Claro", "Light"),
    ("cfg.theme_dark", "Oscuro", "Dark"),
    ("cfg.autostart", "Arrancar con el sistema", "Start with the system"),
    ("cfg.autostart_err", "Autoarranque: {0}", "Autostart: {0}"),
    ("cfg.update_check", "Avisar de versiones nuevas", "Notify about new versions"),
    (
        "cfg.update_check_help",
        "Consulta GitHub una vez al día (solo la página de la última versión) y no envía nada tuyo.",
        "Checks GitHub once a day (only the latest-release page) and sends nothing of yours.",
    ),
    // --- canal de control
    ("err.bad_code", "Código incorrecto o caducado: mira el nuevo bajo el QR del PC", "Wrong or expired code: check the new one under the PC's QR"),
    ("err.bad_token", "Vuelve a escanear el QR", "Scan the QR again"),
    (
        "err.old_qr",
        "{0} ({1}) trae un QR antiguo: en la app, Conectar y luego «Escanear QR del PC»",
        "{0} ({1}) has an old QR: in the app, Connect and then “Scan the PC's QR”",
    ),
    ("err.a_phone", "Un móvil", "A phone"),
    // --- puertos
    ("port.what_phone", "Móvil", "Phone"),
    ("port.cannot_listen", "{0}: no puedo escuchar en {1} {2}: {3}", "{0}: cannot listen on {1} {2}: {3}"),
    (
        "port.busy_unknown",
        "{0}: el puerto {1} {2} está ocupado por otro programa que no he podido identificar; ciérralo (o reinicia) y vuelve a abrir PepoMote",
        "{0}: port {1} {2} is taken by another program I could not identify; close it (or reboot) and open PepoMote again",
    ),
    ("port.same_process", "{0}: el puerto {1} {2} ya está abierto en este mismo proceso", "{0}: port {1} {2} is already open in this very process"),
    (
        "port.freed",
        "Puerto {0} {1} estaba ocupado por {2} (PID {3}): lo he cerrado para que PepoMote funcione",
        "Port {0} {1} was taken by {2} (PID {3}): I closed it so PepoMote can work",
    ),
    (
        "port.busy_known",
        "{0}: el puerto {1} {2} lo tiene {3} (PID {4}) y no he podido cerrarlo (¿va como administrador?): ciérralo tú y vuelve a abrir PepoMote",
        "{0}: port {1} {2} is held by {3} (PID {4}) and I could not close it (running as administrator?): close it yourself and open PepoMote again",
    ),
    // --- inyección
    ("inj.error", "Inyección de entrada: {0}", "Input injection: {0}"),
    (
        "inj.mac_ax_denied",
        "sin permiso de Accesibilidad (mira la tarjeta de permisos de la ventana)",
        "no Accessibility permission (see the permissions card in the window)",
    ),
    (
        "inj.wayland_lost",
        "Inyección de entrada: conexión Wayland perdida, reconectando…",
        "Input injection: Wayland connection lost, reconnecting…",
    ),
    (
        "inj.uinput_denied",
        "sin permiso para /dev/uinput — pulsa «Reparar ahora» o copia el comando de la ventana",
        "no permission for /dev/uinput — press “Fix now” or copy the command from the window",
    ),
    (
        "inj.uinput_missing",
        "el módulo uinput no está cargado (no existe /dev/uinput) — «Reparar ahora» lo carga, o: sudo modprobe uinput",
        "the uinput module is not loaded (/dev/uinput does not exist) — “Fix now” loads it, or: sudo modprobe uinput",
    ),
    ("inj.wayland", "Wayland (puntero virtual)", "Wayland (virtual pointer)"),
    ("inj.wayland_no_kb", "Wayland (puntero virtual; sin teclado virtual)", "Wayland (virtual pointer; no virtual keyboard)"),
    ("inj.wayland_connect", "no se pudo conectar al compositor Wayland ({0})", "could not connect to the Wayland compositor ({0})"),
    ("inj.wayland_globals", "fallo leyendo los globales Wayland ({0})", "failed reading the Wayland globals ({0})"),
    ("inj.wayland_rejected", "el compositor rechazó la inyección ({0})", "the compositor rejected the injection ({0})"),
    // --- teclado del móvil: lo que no se pudo teclear vuelve al que escribió
    ("text.truncated", "El texto era muy largo: escribí los primeros {0} caracteres", "The text was too long: I typed the first {0} characters"),
    ("text.queue_full", "Demasiado texto seguido: descarté el último mensaje", "Too much text at once: I dropped the last message"),
    ("text.os_refused", "El sistema no dejó escribir en la ventana de delante (¿va como administrador?)", "The system refused to type into the window in front (is it running as administrator?)"),
    ("text.folded", "Aquí no se pueden teclear tildes ni signos: {0}", "Accents and symbols cannot be typed here: {0}"),
    ("text.dropped", "No pude escribir: {0}", "I could not type: {0}"),
    // --- pantalla del GamePad
    ("screen.status", "Pantalla del GamePad: {0} fps · {1}×{2} · {3} móvil(es)", "GamePad screen: {0} fps · {1}×{2} · {3} phone(s)"),
    ("screen.no_phone", "Pantalla del GamePad: sin móvil suscrito", "GamePad screen: no phone subscribed"),
    ("screen.unavailable", "La doble pantalla no está disponible en este sistema", "The second screen is not available on this system"),
    ("screen.minimized", "La ventana GamePad View de Cemu estaba minimizada: la abro al fondo", "Cemu's GamePad View window was minimized: opening it in the background"),
    ("screen.no_size", "La ventana GamePad View de Cemu no tiene tamaño", "Cemu's GamePad View window has no size"),
    ("screen.no_bitmap", "No puedo crear el bitmap de captura", "Cannot create the capture bitmap"),
    ("screen.cannot_capture", "Cemu no deja capturar la ventana GamePad View", "Cemu does not allow capturing the GamePad View window"),
    ("screen.open_view", "Abre la vista del GamePad en Cemu (Options → Separate GamePad view)", "Open the GamePad view in Cemu (Options → Separate GamePad view)"),
    ("screen.cemu_closed", "Cemu no está abierto", "Cemu is not open"),
    ("screen.no_x11", "Sin sesión X11: en Wayland lanza Cemu con GDK_BACKEND=x11 para la doble pantalla", "No X11 session: on Wayland launch Cemu with GDK_BACKEND=x11 for the second screen"),
    ("screen.x11_connect", "No puedo conectar con X11: {0}", "Cannot connect to X11: {0}"),
    ("screen.not_visible", "La ventana GamePad View de Cemu no está visible", "Cemu's GamePad View window is not visible"),
    (
        "screen.mac_permission",
        "Para la doble pantalla, PepoMote necesita «Grabación de pantalla» (Ajustes del Sistema → Privacidad y seguridad) y reiniciarse después de concederlo",
        "For the second screen PepoMote needs “Screen Recording” (System Settings → Privacy & Security) and a restart after granting it",
    ),
    ("screen.x11_depth", "Profundidad X11 no soportada: {0}", "Unsupported X11 depth: {0}"),
    // --- Dolphin
    ("dolphin.configured", "Dolphin configurado:", "Dolphin set up:"),
    ("dolphin.configured_after_close", "Dolphin configurado al cerrarse, ábrelo y a jugar:", "Dolphin set up on close, open it and play:"),
    // lo que ven los móviles (banner corto; el detalle queda en la ventana)
    ("dolphin.phone_configured", "Dolphin configurado", "Dolphin set up"),
    ("dolphin.phone_open", "Dolphin abierto: se configurará al cerrarlo", "Dolphin is open: it will be set up when closed"),
    ("dolphin.phone_open_nunchuk", "Dolphin abierto: el Nunchuk se aplica al reabrirlo", "Dolphin is open: the Nunchuk applies when reopened"),
    ("dolphin.details", "adaptador emulado, {0} mando(s){1} · {2}", "emulated adapter, {0} controller(s){1} · {2}"),
    ("dolphin.and_nunchuks", " y {0} Nunchuk(s)", " and {0} Nunchuk(s)"),
    ("dolphin.dirs_one", "carpeta: {0}", "folder: {0}"),
    ("dolphin.dirs_many", "en {0} carpetas: {1}", "in {0} folders: {1}"),
    (
        "dolphin.open_nunchuk",
        "Dolphin está abierto: se configurará solo en cuanto lo cierres (poner o quitar el Nunchuk necesita reabrir Dolphin)",
        "Dolphin is open: it will be set up by itself as soon as you close it (attaching or removing the Nunchuk needs Dolphin reopened)",
    ),
    (
        "dolphin.open",
        "Dolphin está abierto: se configurará solo en cuanto lo cierres; luego ábrelo y a jugar",
        "Dolphin is open: it will be set up by itself as soon as you close it; then open it and play",
    ),
    ("dolphin.error", "Dolphin: {0}", "Dolphin: {0}"),
    ("dolphin.found", "Dolphin encontrado en {0} · {1}", "Dolphin found at {0} · {1}"),
    (
        "dolphin.not_found_manual",
        "No encuentro Dolphin: escribe su carpeta a mano (la del Dolphin.exe)",
        "Cannot find Dolphin: type its folder by hand (the one with Dolphin.exe)",
    ),
    (
        "dolphin.not_found",
        "No encuentro Dolphin en este equipo: ábrelo una vez, o indica su carpeta en Ajustes",
        "Cannot find Dolphin on this computer: open it once, or set its folder in Settings",
    ),
    ("dolphin.why_portable", "portable (portable.txt junto a Dolphin)", "portable (portable.txt next to Dolphin)"),
    ("dolphin.why_local", "junto a Dolphin (LocalUserConfig en el registro)", "next to Dolphin (LocalUserConfig in the registry)"),
    ("dolphin.why_registry", "UserConfigPath del registro", "UserConfigPath from the registry"),
    ("dolphin.why_documents", "Documentos\\Dolphin Emulator", "Documents\\Dolphin Emulator"),
    // --- Cemu
    ("cemu.kind_gamepad", "GamePad", "GamePad"),
    ("cemu.kind_gamepad_screen", "GamePad (solo pantalla)", "GamePad (screen only)"),
    ("cemu.kind_pro", "Pro", "Pro"),
    ("cemu.kind_wiimote_nunchuk", "Mando Wii + Nunchuk", "Wii Remote + Nunchuk"),
    ("cemu.kind_wiimote", "Mando Wii", "Wii Remote"),
    ("cemu.player_kind", "J{0} {1}", "P{0} {1}"),
    (
        "cemu.gamepad_empty",
        "mando 1 GamePad por teclado del PC (Cemu lo necesita; todos sois Mando Wii)",
        "controller 1 GamePad on the PC keyboard (Cemu needs one; everyone is a Wii Remote)",
    ),
    ("cemu.configured", "Cemu configurado:", "Cemu set up:"),
    ("cemu.configured_after_close", "Cemu configurado al cerrarse, ábrelo y a jugar:", "Cemu set up on close, open it and play:"),
    ("cemu.phone_configured", "Cemu configurado", "Cemu set up"),
    ("cemu.phone_open", "Cemu abierto: se configurará al cerrarlo", "Cemu is open: it will be set up when closed"),
    (
        "cemu.phone_not_gamepad",
        "Cemu: el mando 1 no es un GamePad, la pantalla táctil no se aplicará",
        "Cemu: Controller 1 is not a GamePad, the touch screen will not apply",
    ),
    ("cemu.installs", " (en {0} instalaciones)", " (in {0} installs)"),
    (
        "cemu.open",
        "Cemu está abierto: se configurará solo en cuanto lo cierres; luego ábrelo y a jugar",
        "Cemu is open: it will be set up by itself as soon as you close it; then open it and play",
    ),
    ("cemu.error", "Cemu: {0}", "Cemu: {0}"),
    ("cemu.found", "Cemu encontrado en {0}", "Cemu found at {0}"),
    ("cemu.not_found_manual", "No encuentro Cemu: escribe su carpeta a mano", "Cannot find Cemu: type its folder by hand"),
    ("cemu.not_found", "No encuentro Cemu en este equipo: indica su carpeta en Ajustes", "Cannot find Cemu on this computer: set its folder in Settings"),
    ("cemu.settings_no_content", "settings.xml de Cemu sin <content>: no lo toco", "Cemu's settings.xml has no <content>: leaving it alone"),
    // --- modo automático (avisos a los móviles)
    ("auto.dolphin_opened", "Dolphin abierto: modo Dolphin", "Dolphin opened: Dolphin mode"),
    ("auto.cemu_opened", "Cemu abierto: modo Wii U", "Cemu opened: Wii U mode"),
    ("auto.dolphin_closed_cemu", "Dolphin cerrado: modo Wii U (Cemu sigue abierto)", "Dolphin closed: Wii U mode (Cemu is still open)"),
    ("auto.dolphin_closed", "Dolphin cerrado: modo puntero", "Dolphin closed: pointer mode"),
    ("auto.cemu_closed_dolphin", "Cemu cerrado: modo Dolphin (Dolphin sigue abierto)", "Cemu closed: Dolphin mode (Dolphin is still open)"),
    ("auto.cemu_closed", "Cemu cerrado: modo puntero", "Cemu closed: pointer mode"),
    // --- permisos (macOS)
    (
        "mac.ax_needed",
        "PepoMote necesita el permiso de Accesibilidad para mover el cursor y pulsar teclas.",
        "PepoMote needs the Accessibility permission to move the cursor and press keys.",
    ),
    ("mac.ax_open", "Abrir Ajustes → Accesibilidad", "Open Settings → Accessibility"),
    (
        "mac.ax_hint",
        "Marca PepoMote en la lista y vuelve: se activa solo, sin reiniciar.",
        "Tick PepoMote in the list and come back: it activates by itself, no restart.",
    ),
    (
        "mac.screen_needed",
        "Para la doble pantalla de Cemu hace falta «Grabación de pantalla».",
        "Cemu's second screen needs “Screen Recording”.",
    ),
    ("mac.screen_open", "Abrir Ajustes → Grabación de pantalla", "Open Settings → Screen Recording"),
    ("mac.restart", "Reiniciar PepoMote", "Restart PepoMote"),
    (
        "mac.screen_hint",
        "macOS solo aplica este permiso al reiniciar la app; en macOS 15 o más puede recordarte cada mes que PepoMote captura la ventana de Cemu.",
        "macOS applies this permission only after restarting the app; on macOS 15 or later it may remind you monthly that PepoMote captures Cemu's window.",
    ),
    (
        "mac.local_network",
        "Si macOS pregunta por «Red local», acepta: es como el móvil encuentra al PC.",
        "If macOS asks about “Local Network”, allow it: that is how the phone finds the PC.",
    ),
    // --- aviso de versión nueva
    ("upd.available", "PepoMote {0} disponible", "PepoMote {0} available"),
    ("upd.download", "Descargar en GitHub", "Download on GitHub"),
    ("upd.dismiss", "Ocultar", "Hide"),
    // --- bandeja (Windows) / barra de menús (macOS)
    ("tray.waiting", "PepoMote · esperando al móvil", "PepoMote · waiting for the phone"),
    ("tray.line", "PepoMote · {0} {1} · {2}", "PepoMote · {0} {1} · {2}"),
    ("tray.phone_one", "móvil", "phone"),
    ("tray.phone_many", "móviles", "phones"),
    ("tray.mode_pointer", "Puntero", "Pointer"),
    ("tray.mode_dolphin", "Dolphin", "Dolphin"),
    ("tray.mode_cemu", "Wii U", "Wii U"),
    ("tray.mode_switch", "Switch", "Switch"),
    ("tray.show", "Mostrar PepoMote", "Show PepoMote"),
    ("tray.quit", "Salir", "Quit"),
    ("tray.update", "Nueva versión {0}…", "New version {0}…"),
];

/// Fuentes con textos, para el test de completitud de `i18n`.
#[cfg(test)]
pub const SOURCES: &[&str] = &[
    include_str!("app.rs"),
    include_str!("net/control.rs"),
    include_str!("net/telemetry.rs"),
    include_str!("ports.rs"),
    include_str!("fixes.rs"),
    include_str!("launch.rs"),
    include_str!("input/mod.rs"),
    include_str!("input/text_plan.rs"),
    include_str!("input/linux_wayland.rs"),
    include_str!("screen/mod.rs"),
    include_str!("screen/capture_none.rs"),
    include_str!("screen/capture_windows.rs"),
    include_str!("screen/capture_x11.rs"),
    include_str!("screen/capture_macos.rs"),
    include_str!("dolphin.rs"),
    include_str!("cemu.rs"),
    include_str!("eden.rs"),
    include_str!("eden/paths.rs"),
    include_str!("retroarch/mod.rs"),
    include_str!("retroarch/paths.rs"),
    include_str!("retroarch/link.rs"),
    include_str!("auto_mode.rs"),
    include_str!("tray.rs"),
];
