//! Textos del receptor que ve el usuario: (clave, español, inglés). El
//! idioma activo lo pone `i18n`; `tr!("clave")` devuelve el texto y
//! `tr!("clave", a, b)` rellena `{0}`, `{1}`. Un test comprueba que toda
//! clave usada existe, que ninguna sobra y que los huecos coinciden.

pub const TABLE: &[(&str, &str, &str)] = &[
    // --- ventana
    ("win.tagline", "Apunta. Haz clic. Juega.", "Point. Click. Play."),
    ("win.waiting", "Esperando al móvil…", "Waiting for the phone…"),
    ("win.another_player", "¿Otro jugador? Escanea", "Another player? Scan"),
    ("win.footer", "v{0} · pv1 · Inyección: {1}", "v{0} · pv1 · Injection: {1}"),
    ("win.inj_none", "ninguna", "none"),
    ("win.lang_switch", "Cambiar a {0}", "Switch to {0}"),
    ("win.no_camera_code", "Sin cámara: código", "No camera: code"),
    ("win.dolphin_clients", "Dolphin: {0} cliente(s) DSU", "Dolphin: {0} DSU client(s)"),
    ("win.configure_dolphin", "Configurar Dolphin", "Set up Dolphin"),
    (
        "win.dolphin_help",
        "¿Dolphin enseña el mando desconectado? Modo Dolphin en el móvil, juego de Wii, y reinicia Dolphin; la carpeta configurada tiene que ser la suya (en Dolphin: Archivo, «Abrir carpeta de usuario»).",
        "Does Dolphin show the controller disconnected? Dolphin mode on the phone, a Wii game, and restart Dolphin; the configured folder must be Dolphin's own (in Dolphin: File, “Open User Folder”).",
    ),
    ("win.cemu_clients", "Cemu (Wii U): {0} cliente(s) DSU", "Cemu (Wii U): {0} DSU client(s)"),
    ("win.configure_cemu", "Configurar Cemu", "Set up Cemu"),
    (
        "win.cemu_help",
        "Con Cemu cerrado. Jugador 1 = GamePad (y ve la pantalla del GamePad en el móvil), los demás Pro Controller; «Mando de Wii» se elige en el móvil.",
        "With Cemu closed. Player 1 = GamePad (and sees the GamePad screen on the phone), the rest Pro Controller; “Wii Remote” is chosen on the phone.",
    ),
    ("win.mode_pointer", "Modo puntero (apunta el Jugador 1)", "Pointer mode (Player 1 points)"),
    ("win.mode_dolphin", "Modo Dolphin: todos juegan", "Dolphin mode: everyone plays"),
    ("win.mode_cemu", "Modo Wii U (Cemu): todos juegan", "Wii U mode (Cemu): everyone plays"),
    ("win.pps", "{0} paquetes/s · sensor {1} Hz", "{0} packets/s · sensor {1} Hz"),
    ("win.heartbeat_tip", "Latido del Jugador 1: {0} ms ahora (últimos {1} latidos)", "Player 1 heartbeat: {0} ms now (last {1} beats)"),
    ("win.badge_nunchuk_unused", "J{0} · Nunchuk (sin uso: J{0} no es Mando Wii)", "P{0} · Nunchuk (unused: P{0} is not a Wii Remote)"),
    ("win.badge_nunchuk", "J{0} · Nunchuk", "P{0} · Nunchuk"),
    ("win.badge_gamepad", "J{0} · GamePad", "P{0} · GamePad"),
    ("win.badge_pro", "J{0} · Pro", "P{0} · Pro"),
    ("win.badge_wiimote", "J{0} · Mando Wii", "P{0} · Wii Remote"),
    ("win.badge_player", "J{0}", "P{0}"),
    // --- reparación (Linux)
    (
        "fix.uinput_missing",
        "El módulo uinput no está cargado (no existe /dev/uinput): sin él no puedo mover el cursor.",
        "The uinput module is not loaded (/dev/uinput does not exist): without it I cannot move the cursor.",
    ),
    ("fix.uinput_denied", "Sin permiso para mover el cursor (/dev/uinput).", "No permission to move the cursor (/dev/uinput)."),
    ("fix.applying", "Aplicando… responde al diálogo de contraseña", "Applying… answer the password dialog"),
    ("fix.retry", "🔧 Reintentar", "🔧 Retry"),
    ("fix.now", "🔧 Reparar ahora", "🔧 Fix now"),
    ("fix.dialog_once", "Un diálogo del sistema pedirá tu contraseña una sola vez", "A system dialog will ask for your password just once"),
    (
        "fix.manual_no_dialog",
        "Si el diálogo no aparece (sesión sin agente de polkit), pega esto en un terminal:",
        "If the dialog does not appear (session without a polkit agent), paste this in a terminal:",
    ),
    (
        "fix.manual_no_pkexec",
        "No hay pkexec en este sistema. Pega esto en un terminal (pide tu contraseña una vez):",
        "There is no pkexec on this system. Paste this in a terminal (it asks for your password once):",
    ),
    ("fix.copy_cmd", "Copiar comando", "Copy command"),
    ("fix.copied", "Copiado", "Copied"),
    (
        "fix.relogin",
        "Si después sigue sin permiso, cierra sesión y vuelve a entrar (la regla se aplica al iniciar sesión).",
        "If it still has no permission afterwards, log out and back in (the rule applies at login).",
    ),
    (
        "fix.no_auth",
        "No se pudo autenticar: en esta sesión no hay agente de polkit (nadie puede pedir la contraseña) o la contraseña no era válida",
        "Could not authenticate: this session has no polkit agent (nobody can ask for the password) or the password was not valid",
    ),
    ("fix.polkit_silent", "polkit no responde: {0}", "polkit is not responding: {0}"),
    ("fix.exit_code", "código {0}", "code {0}"),
    ("fix.signal", "terminado por una señal", "killed by a signal"),
    ("fix.failed", "Reparación fallida: {0}", "Repair failed: {0}"),
    ("fix.no_pkexec_launch", "No pude lanzar pkexec: {0}", "Could not launch pkexec: {0}"),
    // --- ajustes
    ("cfg.title", "Ajustes", "Settings"),
    ("cfg.sensitivity", "Sensibilidad", "Sensitivity"),
    ("cfg.sens_help", "Grados de giro para cruzar la pantalla (menos = más rápido)", "Degrees of turn to cross the screen (less = faster)"),
    ("cfg.abs", "Apuntado absoluto", "Absolute pointing"),
    (
        "cfg.abs_help",
        "Activado: el cursor está donde apunta el móvil, y vuelve al mismo sitio si vuelves a apuntar igual (la altura la fija la gravedad; el giro, el último recentrado). El recorrido es exacto: Windows no le aplica su aceleración de ratón.\n\nDesactivado (relativo): como un ratón, solo cuentan los desplazamientos, con la aceleración del sistema si la tienes activada. Es el modo para juegos que capturan el ratón.\n\nEn movimiento los dos son idénticos (1:1 con el giroscopio). Home recentra en los dos.",
        "On: the cursor is where the phone points, and it returns to the same spot if you point the same way again (height comes from gravity; turn, from the last recenter). The travel is exact: Windows applies no mouse acceleration to it.\n\nOff (relative): like a mouse, only the movement counts, with the system acceleration if you have it on. This is the mode for games that capture the mouse.\n\nWhile moving both are identical (1:1 with the gyroscope). Home recenters in both.",
    ),
    ("cfg.auto_dolphin", "Configurar Dolphin automáticamente (multijugador)", "Set up Dolphin automatically (multiplayer)"),
    ("cfg.auto_cemu", "Configurar Cemu automáticamente (modo Wii U)", "Set up Cemu automatically (Wii U mode)"),
    ("cfg.auto_mode", "Cambiar de modo al abrir o cerrar Dolphin o Cemu", "Switch mode when Dolphin or Cemu opens or closes"),
    (
        "cfg.auto_mode_help",
        "Al abrir Dolphin el receptor pasa a modo Dolphin; al abrir Cemu, a Wii U; al cerrarlos, vuelve al puntero (o al otro emulador si sigue abierto). Los móviles cambian de pantalla solos y ven un aviso.\n\nLo que elijas a mano en el móvil se respeta hasta la siguiente vez que abras o cierres un emulador.",
        "When Dolphin opens the receiver switches to Dolphin mode; when Cemu opens, to Wii U; when they close, back to the pointer (or to the other emulator if it is still open). The phones switch screens by themselves and see a notice.\n\nWhatever you choose by hand on the phone is respected until the next time an emulator opens or closes.",
    ),
    ("cfg.cemu_folder", "Carpeta de Cemu", "Cemu folder"),
    ("cfg.auto_hint", "automática", "automatic"),
    ("cfg.detect", "Detectar", "Detect"),
    (
        "cfg.cemu_folder_help",
        "Solo hace falta si Cemu está en un sitio raro; se aprende sola al verlo abierto.",
        "Only needed if Cemu lives somewhere unusual; it is learned by itself when Cemu is seen open.",
    ),
    ("cfg.dolphin_folder", "Carpeta de Dolphin", "Dolphin folder"),
    (
        "cfg.dolphin_folder_help",
        "La del Dolphin.exe. Un Dolphin portable (RetroBat, LaunchBox…) guarda su configuración ahí; se aprende sola al verlo abierto.",
        "The one with Dolphin.exe. A portable Dolphin (RetroBat, LaunchBox…) keeps its configuration there; it is learned by itself when Dolphin is seen open.",
    ),
    ("cfg.pointing_on", "Apuntado absoluto en", "Absolute pointing on"),
    ("cfg.all_screens", "Todas las pantallas", "All screens"),
    ("cfg.only_screen", "Solo {0} ({1}×{2})", "Only {0} ({1}×{2})"),
    (
        "cfg.screens_help",
        "Todas = el cursor llega a los tres monitores. Una sola = apuntado preciso para jugar.",
        "All = the cursor reaches every monitor. One = precise pointing for games.",
    ),
    ("cfg.theme", "Tema", "Theme"),
    ("cfg.theme_system", "Como el sistema", "Like the system"),
    ("cfg.theme_light", "Claro", "Light"),
    ("cfg.theme_dark", "Oscuro", "Dark"),
    ("cfg.autostart", "Arrancar con el sistema", "Start with the system"),
    ("cfg.autostart_err", "Autoarranque: {0}", "Autostart: {0}"),
    // --- canal de control
    ("err.bad_code", "Código incorrecto o caducado: mira el nuevo bajo el QR del PC", "Wrong or expired code: check the new one under the PC's QR"),
    ("err.bad_token", "Vuelve a escanear el QR", "Scan the QR again"),
    (
        "err.old_qr",
        "{0} ({1}) trae un QR antiguo: en la app, Conectar y luego «Escanear QR del PC»",
        "{0} ({1}) has an old QR: in the app, Connect and then “Scan the PC's QR”",
    ),
    ("err.a_phone", "Un móvil", "A phone"),
    // --- puertos
    ("port.what_phone", "Móvil", "Phone"),
    ("port.cannot_listen", "{0}: no puedo escuchar en {1} {2}: {3}", "{0}: cannot listen on {1} {2}: {3}"),
    (
        "port.busy_unknown",
        "{0}: el puerto {1} {2} está ocupado por otro programa que no he podido identificar; ciérralo (o reinicia) y vuelve a abrir PepoMote",
        "{0}: port {1} {2} is taken by another program I could not identify; close it (or reboot) and open PepoMote again",
    ),
    ("port.same_process", "{0}: el puerto {1} {2} ya está abierto en este mismo proceso", "{0}: port {1} {2} is already open in this very process"),
    (
        "port.freed",
        "Puerto {0} {1} estaba ocupado por {2} (PID {3}): lo he cerrado para que PepoMote funcione",
        "Port {0} {1} was taken by {2} (PID {3}): I closed it so PepoMote can work",
    ),
    (
        "port.busy_known",
        "{0}: el puerto {1} {2} lo tiene {3} (PID {4}) y no he podido cerrarlo (¿va como administrador?): ciérralo tú y vuelve a abrir PepoMote",
        "{0}: port {1} {2} is held by {3} (PID {4}) and I could not close it (running as administrator?): close it yourself and open PepoMote again",
    ),
    // --- inyección
    ("inj.error", "Inyección de entrada: {0}", "Input injection: {0}"),
    (
        "inj.wayland_lost",
        "Inyección de entrada: conexión Wayland perdida, reconectando…",
        "Input injection: Wayland connection lost, reconnecting…",
    ),
    (
        "inj.uinput_denied",
        "sin permiso para /dev/uinput — pulsa «Reparar ahora» o copia el comando de la ventana",
        "no permission for /dev/uinput — press “Fix now” or copy the command from the window",
    ),
    (
        "inj.uinput_missing",
        "el módulo uinput no está cargado (no existe /dev/uinput) — «Reparar ahora» lo carga, o: sudo modprobe uinput",
        "the uinput module is not loaded (/dev/uinput does not exist) — “Fix now” loads it, or: sudo modprobe uinput",
    ),
    ("inj.wayland", "Wayland (puntero virtual)", "Wayland (virtual pointer)"),
    ("inj.wayland_no_kb", "Wayland (puntero virtual; sin teclado virtual)", "Wayland (virtual pointer; no virtual keyboard)"),
    ("inj.wayland_connect", "no se pudo conectar al compositor Wayland ({0})", "could not connect to the Wayland compositor ({0})"),
    ("inj.wayland_globals", "fallo leyendo los globales Wayland ({0})", "failed reading the Wayland globals ({0})"),
    ("inj.wayland_rejected", "el compositor rechazó la inyección ({0})", "the compositor rejected the injection ({0})"),
    // --- pantalla del GamePad
    ("screen.status", "Pantalla del GamePad: {0} fps · {1}×{2} · {3} móvil(es)", "GamePad screen: {0} fps · {1}×{2} · {3} phone(s)"),
    ("screen.no_phone", "Pantalla del GamePad: sin móvil suscrito", "GamePad screen: no phone subscribed"),
    ("screen.unavailable", "La doble pantalla no está disponible en este sistema", "The second screen is not available on this system"),
    ("screen.minimized", "La ventana GamePad View de Cemu estaba minimizada: la abro al fondo", "Cemu's GamePad View window was minimized: opening it in the background"),
    ("screen.no_size", "La ventana GamePad View de Cemu no tiene tamaño", "Cemu's GamePad View window has no size"),
    ("screen.no_bitmap", "No puedo crear el bitmap de captura", "Cannot create the capture bitmap"),
    ("screen.cannot_capture", "Cemu no deja capturar la ventana GamePad View", "Cemu does not allow capturing the GamePad View window"),
    ("screen.open_view", "Abre la vista del GamePad en Cemu (Options → Separate GamePad view)", "Open the GamePad view in Cemu (Options → Separate GamePad view)"),
    ("screen.cemu_closed", "Cemu no está abierto", "Cemu is not open"),
    ("screen.no_x11", "Sin sesión X11: en Wayland lanza Cemu con GDK_BACKEND=x11 para la doble pantalla", "No X11 session: on Wayland launch Cemu with GDK_BACKEND=x11 for the second screen"),
    ("screen.x11_connect", "No puedo conectar con X11: {0}", "Cannot connect to X11: {0}"),
    ("screen.not_visible", "La ventana GamePad View de Cemu no está visible", "Cemu's GamePad View window is not visible"),
    ("screen.x11_depth", "Profundidad X11 no soportada: {0}", "Unsupported X11 depth: {0}"),
    // --- Dolphin
    ("dolphin.configured", "Dolphin configurado:", "Dolphin set up:"),
    ("dolphin.configured_after_close", "Dolphin configurado al cerrarse, ábrelo y a jugar:", "Dolphin set up on close, open it and play:"),
    ("dolphin.details", "adaptador emulado, {0} mando(s){1} · {2}", "emulated adapter, {0} controller(s){1} · {2}"),
    ("dolphin.and_nunchuks", " y {0} Nunchuk(s)", " and {0} Nunchuk(s)"),
    ("dolphin.dirs_one", "carpeta: {0}", "folder: {0}"),
    ("dolphin.dirs_many", "en {0} carpetas: {1}", "in {0} folders: {1}"),
    (
        "dolphin.open_nunchuk",
        "Dolphin está abierto: se configurará solo en cuanto lo cierres (el Nunchuk necesita reabrir Dolphin)",
        "Dolphin is open: it will be set up by itself as soon as you close it (the Nunchuk needs Dolphin reopened)",
    ),
    (
        "dolphin.open",
        "Dolphin está abierto: se configurará solo en cuanto lo cierres; luego ábrelo y a jugar",
        "Dolphin is open: it will be set up by itself as soon as you close it; then open it and play",
    ),
    ("dolphin.error", "Dolphin: {0}", "Dolphin: {0}"),
    ("dolphin.found", "Dolphin encontrado en {0} · {1}", "Dolphin found at {0} · {1}"),
    (
        "dolphin.not_found_manual",
        "No encuentro Dolphin: escribe su carpeta a mano (la del Dolphin.exe)",
        "Cannot find Dolphin: type its folder by hand (the one with Dolphin.exe)",
    ),
    (
        "dolphin.not_found",
        "No encuentro Dolphin en este equipo: ábrelo una vez, o indica su carpeta en Ajustes",
        "Cannot find Dolphin on this computer: open it once, or set its folder in Settings",
    ),
    ("dolphin.why_portable", "portable (portable.txt junto a Dolphin)", "portable (portable.txt next to Dolphin)"),
    ("dolphin.why_local", "junto a Dolphin (LocalUserConfig en el registro)", "next to Dolphin (LocalUserConfig in the registry)"),
    ("dolphin.why_registry", "UserConfigPath del registro", "UserConfigPath from the registry"),
    ("dolphin.why_documents", "Documentos\\Dolphin Emulator", "Documents\\Dolphin Emulator"),
    // --- Cemu
    ("cemu.kind_gamepad", "GamePad", "GamePad"),
    ("cemu.kind_pro", "Pro", "Pro"),
    ("cemu.kind_wiimote_nunchuk", "Mando Wii + Nunchuk", "Wii Remote + Nunchuk"),
    ("cemu.kind_wiimote", "Mando Wii", "Wii Remote"),
    ("cemu.player_kind", "J{0} {1}", "P{0} {1}"),
    ("cemu.configured", "Cemu configurado:", "Cemu set up:"),
    ("cemu.configured_after_close", "Cemu configurado al cerrarse, ábrelo y a jugar:", "Cemu set up on close, open it and play:"),
    ("cemu.installs", " (en {0} instalaciones)", " (in {0} installs)"),
    (
        "cemu.open",
        "Cemu está abierto: se configurará solo en cuanto lo cierres; luego ábrelo y a jugar",
        "Cemu is open: it will be set up by itself as soon as you close it; then open it and play",
    ),
    ("cemu.error", "Cemu: {0}", "Cemu: {0}"),
    ("cemu.found", "Cemu encontrado en {0}", "Cemu found at {0}"),
    ("cemu.not_found_manual", "No encuentro Cemu: escribe su carpeta a mano", "Cannot find Cemu: type its folder by hand"),
    ("cemu.not_found", "No encuentro Cemu en este equipo: indica su carpeta en Ajustes", "Cannot find Cemu on this computer: set its folder in Settings"),
    ("cemu.settings_no_content", "settings.xml de Cemu sin <content>: no lo toco", "Cemu's settings.xml has no <content>: leaving it alone"),
    // --- modo automático (avisos a los móviles)
    ("auto.dolphin_opened", "Dolphin abierto: modo Dolphin", "Dolphin opened: Dolphin mode"),
    ("auto.cemu_opened", "Cemu abierto: modo Wii U", "Cemu opened: Wii U mode"),
    ("auto.dolphin_closed_cemu", "Dolphin cerrado: modo Wii U (Cemu sigue abierto)", "Dolphin closed: Wii U mode (Cemu is still open)"),
    ("auto.dolphin_closed", "Dolphin cerrado: modo puntero", "Dolphin closed: pointer mode"),
    ("auto.cemu_closed_dolphin", "Cemu cerrado: modo Dolphin (Dolphin sigue abierto)", "Cemu closed: Dolphin mode (Dolphin is still open)"),
    ("auto.cemu_closed", "Cemu cerrado: modo puntero", "Cemu closed: pointer mode"),
    // --- bandeja (Windows)
    ("tray.waiting", "PepoMote · esperando al móvil", "PepoMote · waiting for the phone"),
    ("tray.line", "PepoMote · {0} {1} · {2}", "PepoMote · {0} {1} · {2}"),
    ("tray.phone_one", "móvil", "phone"),
    ("tray.phone_many", "móviles", "phones"),
    ("tray.mode_pointer", "Puntero", "Pointer"),
    ("tray.mode_dolphin", "Dolphin", "Dolphin"),
    ("tray.mode_cemu", "Wii U", "Wii U"),
    ("tray.show", "Mostrar PepoMote", "Show PepoMote"),
    ("tray.quit", "Salir", "Quit"),
];

/// Fuentes con textos, para el test de completitud de `i18n`.
#[cfg(test)]
pub const SOURCES: &[&str] = &[
    include_str!("app.rs"),
    include_str!("net/control.rs"),
    include_str!("net/telemetry.rs"),
    include_str!("ports.rs"),
    include_str!("fixes.rs"),
    include_str!("input/mod.rs"),
    include_str!("input/linux_wayland.rs"),
    include_str!("screen/mod.rs"),
    include_str!("screen/capture_none.rs"),
    include_str!("screen/capture_windows.rs"),
    include_str!("screen/capture_x11.rs"),
    include_str!("dolphin.rs"),
    include_str!("cemu.rs"),
    include_str!("auto_mode.rs"),
    include_str!("tray.rs"),
];
