//! Textos del móvil Linux que ve el usuario: (clave, español, inglés). El
//! idioma activo lo pone `i18n` (compartido con el receptor); `tr!("clave")`
//! devuelve el texto y `tr!("clave", a, b)` rellena `{0}`, `{1}`.

pub const TABLE: &[(&str, &str, &str)] = &[
    // --- común
    ("common.connecting", "Conectando…", "Connecting…"),
    ("common.reconnecting", "Reconectando…", "Reconnecting…"),
    ("common.no_connection", "Sin conexión", "No connection"),
    ("common.reconnect", "Reconectar", "Reconnect"),
    ("common.back", "Volver", "Back"),
    ("common.exit", "Salir", "Exit"),
    ("common.keyboard", "Teclado", "Keyboard"),
    ("common.mode_pointer", "Puntero", "Pointer"),
    ("common.mode_dolphin", "Dolphin", "Dolphin"),
    ("common.mode_cemu", "Wii U", "Wii U"),
    ("common.in_cemu", "En Cemu soy:", "In Cemu I am:"),
    ("common.gamepad", "GamePad", "GamePad"),
    ("common.pro", "Pro Controller", "Pro Controller"),
    ("common.wiimote", "Mando de Wii", "Wii Remote"),
    ("common.mode_switch", "Switch", "Switch"),
    ("common.mode_retroarch", "RetroArch", "RetroArch"),
    ("common.in_retroarch", "En RetroArch soy:", "In RetroArch I am:"),
    ("common.nes_pad", "Mando Wii", "Wii Remote"),
    ("common.light_gun", "Pistola", "Light gun"),
    ("gp.fast", "Rápido", "Fast"),
    ("gp.menu", "Menú", "Menu"),
    ("gp.activating_retroarch", "Activando RetroArch…", "Activating RetroArch…"),
    ("home.card_retroarch", "RetroArch", "RetroArch"),
    ("home.card_retroarch_sub", "El mando de cada consola, Mando Wii o pistola", "Each console's pad, Wii Remote or light gun"),
    ("notice.old_pc_retroarch", "El PC necesita un PepoMote más nuevo para RetroArch", "The PC needs a newer PepoMote for RetroArch"),
    ("ctl.retro_pad_help", "Consola: el mando del juego que carga RetroArch (tócalo para elegir otro) · Mando Wii: apunta en PC; B y A · Pistola: apunta con el móvil, B dispara y A recarga", "Console: the pad of the game RetroArch loads (tap it to pick another) · Wii Remote: aim on PC; B and A · Light gun: aim with the phone, B fires and A reloads"),
    ("gp.layout_title", "Mando en RetroArch", "Pad in RetroArch"),
    ("gp.layout_auto", "Automático ({0})", "Automatic ({0})"),
    ("gp.layout_full", "RetroPad completo", "Full RetroPad"),
    ("gp.layout_hint_game", "Se recuerda para {0}", "Remembered for {0}"),
    ("gp.layout_hint_no_game", "Hasta que RetroArch cargue un juego", "Until RetroArch loads a game"),
    ("gp.layout_changed", "Mando: {0}", "Pad: {0}"),
    ("gp.coin", "Moneda", "Coin"),
    ("gp.fire", "Disparo", "Fire"),
    ("hk.save", "Guardar", "Save"),
    ("hk.load", "Cargar", "Load"),
    ("hk.slot_minus", "Ranura −", "Slot −"),
    ("hk.slot_plus", "Ranura +", "Slot +"),
    ("hk.rewind", "Rebobinar", "Rewind"),
    ("hk.pause", "Pausa", "Pause"),
    ("hk.screenshot", "Captura", "Screenshot"),
    ("hk.reset", "Reiniciar", "Reset"),
    ("kb.title_retroarch", "Teclado para RetroArch", "Keyboard for RetroArch"),
    ("gp.capture", "Capturar", "Capture"),
    ("gp.activating_switch", "Activando Switch…", "Activating Switch…"),
    ("home.card_switch", "Switch", "Switch"),
    ("home.card_switch_sub", "Pro Controller para Eden", "Pro Controller for Eden"),
    ("notice.old_pc_switch", "El PC necesita un PepoMote más nuevo para Switch", "The PC needs a newer PepoMote for Switch"),
    // --- inicio
    ("home.tagline", "Apunta. Haz clic. Juega.", "Point. Click. Play."),
    ("home.lang_switch", "Cambiar a {0}", "Switch to {0}"),
    ("home.connected", "Conectado a {0}", "Connected to {0}"),
    ("home.reconnecting", "Reconectando con {0}…", "Reconnecting to {0}…"),
    ("home.paired", "Emparejado con {0} · sin conexión", "Paired with {0} · no connection"),
    ("home.unpaired", "Sin emparejar: toca Conectar", "Not paired: tap Connect"),
    ("home.card_connect", "Conectar", "Connect"),
    ("home.card_connect_sub", "apunta y haz clic", "point and click"),
    ("home.card_pad", "Mando", "Controller"),
    ("home.card_pad_sub", "solo botones", "buttons only"),
    ("home.card_dolphin", "Dolphin", "Dolphin"),
    ("home.card_dolphin_sub", "Wiimote virtual", "virtual Wiimote"),
    ("home.card_nunchuk", "Nunchuk", "Nunchuk"),
    ("home.card_nunchuk_sub", "la otra mano", "the other hand"),
    ("home.card_wiiu", "Wii U", "Wii U"),
    ("home.card_wiiu_sub", "GamePad para Cemu", "GamePad for Cemu"),
    ("home.card_pair", "Emparejar", "Pair"),
    ("home.card_pair_sub", "otro PC / código", "another PC / code"),
    ("home.sensors", "Sensores: {0}", "Sensors: {0}"),
    ("home.controls_only", "Sin sensores de movimiento · botones y sticks disponibles", "No motion sensors · buttons and sticks available"),
    ("home.no_sensors", "sin sensores: {0}", "no sensors: {0}"),
    ("home.calibrate", "Calibrar sensores", "Calibrate sensors"),
    (
        "home.calibrate_tip",
        "Si el puntero va al revés o a tirones: seis posturas guiadas y listo",
        "If the pointer goes backwards or jerks: six guided poses and done",
    ),
    ("home.theme", "Tema", "Theme"),
    ("home.theme_system", "Sistema", "System"),
    ("home.theme_light", "Claro", "Light"),
    ("home.theme_dark", "Oscuro", "Dark"),
    ("home.version", "v{0} · pv1 · Linux móvil", "v{0} · pv1 · Linux phone"),
    // --- aviso de versión nueva
    ("upd.toggle", "Avisar de versiones nuevas", "Notify about new versions"),
    (
        "upd.toggle_help",
        "Busca nuevas versiones al arrancar y cada hora en GitHub. La descarga solo empieza cuando pulsas Instalar.",
        "Checks GitHub at startup and hourly. Downloading starts only when you press Install.",
    ),
    // --- emparejar
    ("pair.title", "Conectar", "Connect"),
    ("pair.title_again", "Vuelve a emparejar", "Pair again"),
    (
        "pair.subtitle",
        "Abre PepoMote en tu PC. Elige tu PC y teclea el código de 4 dígitos que hay bajo su QR.",
        "Open PepoMote on your PC. Pick your PC and type the 4-digit code under its QR.",
    ),
    ("pair.your_pcs", "Tus PCs", "Your PCs"),
    ("pair.current", " · actual", " · current"),
    ("pair.online", " · en la red", " · on the network"),
    ("pair.forget", "Olvidar", "Forget"),
    ("pair.scanning", "Buscando receptores en tu red…", "Looking for receivers on your network…"),
    (
        "pair.none",
        "Ningún receptor a la vista (¿misma Wi-Fi?). Puedes escribir la IP a mano.",
        "No receiver in sight (same Wi-Fi?). You can type the IP by hand.",
    ),
    ("pair.on_network", "En tu red:", "On your network:"),
    ("pair.manual_ip", "Escribir IP a mano", "Type the IP by hand"),
    ("pair.your_pc", "Tu PC", "Your PC"),
    (
        "pair.not_responding",
        "{0} no responde. Elige otro PC o teclea el código de otro.",
        "{0} is not responding. Pick another PC or type another one's code.",
    ),
    (
        "pair.re_pair",
        "{0} ya no reconoce este móvil: su emparejamiento ha cambiado (PepoMote reinstalado o restablecido en el PC). Elige tu PC y teclea el código nuevo que hay bajo su QR.",
        "{0} no longer recognises this phone: its pairing has changed (PepoMote reinstalled or reset on the PC). Pick your PC and type the new code under its QR.",
    ),
    ("manual.title", "IP del PC", "PC's IP"),
    ("manual.subtitle", "La que muestra el receptor bajo el QR (IP : puerto)", "The one the receiver shows under the QR (IP : port)"),
    ("code.title", "Código", "Code"),
    ("code.subtitle", "Los 4 dígitos bajo el QR de {0}", "The 4 digits under {0}'s QR"),
    ("code.pairing", "Emparejando…", "Pairing…"),
    // --- mando
    ("ctl.title_player", "{0} · Jugador {1}", "{0} · Player {1}"),
    ("ctl.wiiu_wiimote", "Wii U · Mando de Wii", "Wii U · Wii Remote"),
    ("ctl.pointer_p1", "Puntero: apunta el Jugador 1", "Pointer: Player 1 points"),
    (
        "ctl.pad_help",
        "Para juegos de Wii U que se juegan con el mando de Wii (Wii Sports Club, Wii Party U…)",
        "For Wii U games played with the Wii Remote (Wii Sports Club, Wii Party U…)",
    ),
    ("ctl.media_open", "Multimedia ▲", "Media ▲"),
    ("ctl.media_closed", "Multimedia ▼", "Media ▼"),
    // --- GamePad
    ("gp.rotate_left", "Giro ◀", "Turn ◀"),
    ("gp.rotate_right", "Giro ▶", "Turn ▶"),
    ("gp.title", "{0} · J{1} · {2}", "{0} · P{1} · {2}"),
    ("gp.screen_fps", " · pantalla · {0} fps", " · screen · {0} fps"),
    ("gp.tv_pad", "TV/Pad", "TV/Pad"),
    ("gp.blow", "Soplar", "Blow"),
    ("gp.veil_wiimote", "Ahora eres Mando de Wii", "You are now a Wii Remote"),
    ("gp.veil_switching", "Cambiando el PC a Wii U…", "Switching the PC to Wii U…"),
    ("gp.touch", "Pantalla táctil", "Touch screen"),
    ("home.notices", "Avisos del PC en pantalla", "PC notices on screen"),
    (
        "home.notices_help",
        "«Dolphin configurado…», «Cemu está abierto…»: salen unos segundos sobre el mando al cambiar de modo. Apágalos si te estorban",
        "\"Dolphin set up…\", \"Cemu is open…\": shown for a few seconds over the controller when the mode changes. Turn them off if they get in the way",
    ),
    ("gp.no_screen", "GamePad sin pantalla táctil", "GamePad without touch screen"),
    (
        "gp.no_screen_help",
        "Quita la pantalla del GamePad de Wii U (y la doble pantalla) para que los botones sean más grandes",
        "Removes the Wii U GamePad's screen (and the second screen) so the buttons get bigger",
    ),
    ("gp.full_screen", "Pantalla del GamePad a pantalla completa", "GamePad screen full screen"),
    (
        "gp.full_screen_help",
        "Para jugar con un mando de verdad conectado al PC: el móvil solo enseña la pantalla del GamePad de Cemu (y responde al tacto), sin sticks ni botones. Al entrar en Wii U como GamePad",
        "To play with a real controller plugged into the PC: the phone only shows Cemu's GamePad screen (and takes touch), no sticks or buttons. When entering Wii U as the GamePad",
    ),
    ("gp.full_screen_kb", "Botón de teclado", "Keyboard button"),
    (
        "gp.full_screen_kb_help",
        "Un botón pequeño arriba a la derecha para escribir en el teclado en pantalla de Cemu",
        "A small button at the top right to type into Cemu's on-screen keyboard",
    ),
    ("gp.full_screen_old_pc", "El receptor no conoce la pantalla completa: actualízalo", "The receiver does not know about full screen: update it"),
    ("home.slide_press", "Pulsar deslizando", "Slide to press"),
    (
        "home.slide_press_help",
        "El botón por el que pasa el dedo se pulsa; al salir se suelta y se pulsa el siguiente",
        "The button your finger slides over gets pressed; leaving it releases it and presses the next one",
    ),
    ("home.sticky_press", "Mantener al salir del botón", "Keep pressed when leaving the button"),
    (
        "home.sticky_press_help",
        "Un botón pulsado sigue pulsado mientras no levantes el dedo, aunque se salga",
        "A pressed button stays pressed until you lift your finger, even if it drifts off",
    ),
    // --- Nunchuk
    ("nk.line", "Nunchuk · Jugador {0} · {1}", "Nunchuk · Player {0} · {1}"),
    ("nk.old_pc", "El PC te ve como mando: actualiza el receptor", "The PC sees you as a controller: update the receiver"),
    (
        "nk.help",
        "En Wii U el Nunchuk solo funciona si el mando elige Mando de Wii",
        "On Wii U the Nunchuk only works if the controller picks Wii Remote",
    ),
    // --- teclado
    ("kb.space", "espacio", "space"),
    ("kb.title_switch", "Teclado para Switch", "Keyboard for Switch"),
    ("kb.title", "Teclado para Cemu", "Keyboard for Cemu"),
    (
        "kb.subtitle",
        "Lo que escribas va al teclado en pantalla del juego. El mando sigue funcionando.",
        "What you type goes to the game's on-screen keyboard. The controller keeps working.",
    ),
    ("kb.placeholder", "Escribe aquí…", "Type here…"),
    ("kb.delete", "Borrar", "Delete"),
    ("kb.write", "Escribir", "Type"),
    ("kb.accept", "Aceptar", "Accept"),
    (
        "kb.help",
        "Borrar quita una letra en el juego · Escribir la teclea · Aceptar la teclea y confirma",
        "Delete removes a letter in the game · Type types it · Accept types it and confirms",
    ),
    ("kb.close", "Cerrar", "Close"),
    // teclado del modo puntero: se escribe donde esté el cursor del PC
    ("kb.title_pointer", "Escribir en el PC", "Type on the PC"),
    ("kb.send", "Enviar", "Send"),
    ("kb.enter", "Enviar + ⏎", "Send + ⏎"),
    (
        "kb.help_pointer",
        "Borrar quita una letra · Enviar pega el texto tal cual · Enviar + ⏎ lo manda y pulsa Intro (buscar, ir a una dirección)",
        "Delete removes a letter · Send pastes the text as is · Send + ⏎ types it and presses Enter (search, go to an address)",
    ),
    (
        "home.kb_click",
        "Clic antes de escribir",
        "Click before typing",
    ),
    (
        "home.kb_click_help",
        "El botón Teclado hace primero un clic izquierdo donde apuntas, para dejar el cursor en el campo. Apagado, haz tú el clic con A antes de escribir.",
        "The Keyboard button first left-clicks where you are pointing, to put the caret in the field. When off, click with A yourself before typing.",
    ),
    // --- calibración
    ("cal.title", "Calibrar sensores", "Calibrate sensors"),
    (
        "cal.subtitle",
        "Tres posturas quietas y tres gestos: así sé hacia dónde mira cada eje de tus sensores.",
        "Three still poses and three gestures: that is how I learn which way each sensor axis points.",
    ),
    ("cal.done", "Listo. Calibración guardada:", "Done. Calibration saved:"),
    ("cal.identity", "Todos los ejes ya venían bien.", "All axes were already right."),
    ("cal.inverted", "Los ejes marcados con - se invierten a partir de ahora.", "Axes marked with - are inverted from now on."),
    ("cal.step_of", "Paso {0} de {1}", "Step {0} of {1}"),
    ("cal.go", "¡Ya! Mueve", "Now! Move"),
    ("cal.measuring", "Midiendo", "Measuring"),
    ("cal.countdown", "{0}… {1} s", "{0}… {1} s"),
    ("cal.ready", "Listo", "Ready"),
    ("cal.waiting", "Esperando muestras del sensor…", "Waiting for sensor samples…"),
    ("cal.cancel", "Cancelar", "Cancel"),
    ("cal.clear", "Borrar calibración", "Clear calibration"),
    ("cal.open_err", "No puedo abrir los sensores para calibrar: {0}", "Cannot open the sensors to calibrate: {0}"),
    ("cal.step1_title", "1 · Plano boca arriba", "1 · Flat, face up"),
    (
        "cal.step1_text",
        "Deja el móvil plano sobre la mesa, con la pantalla hacia arriba, y pulsa Listo.",
        "Lay the phone flat on the table, screen up, and press Ready.",
    ),
    ("cal.step2_title", "2 · De pie", "2 · Standing"),
    (
        "cal.step2_text",
        "Ponlo de pie, apoyado en el borde de abajo (el del USB), con la pantalla hacia ti, como si lo estuvieras leyendo. Sujétalo quieto y pulsa Listo.",
        "Stand it on its bottom edge (the USB one), screen facing you, as if you were reading it. Hold it still and press Ready.",
    ),
    ("cal.step3_title", "3 · Sobre el lado izquierdo", "3 · On its left side"),
    (
        "cal.step3_text",
        "Túmbalo de canto sobre su lado IZQUIERDO, con la pantalla hacia ti: queda apaisado, con la cámara hacia tu izquierda. Quieto, y pulsa Listo.",
        "Lay it on its LEFT side, screen facing you: landscape, camera to your left. Still, and press Ready.",
    ),
    ("cal.step4_title", "4 · Levanta el borde superior", "4 · Lift the top edge"),
    (
        "cal.step4_text",
        "Déjalo plano. Al pulsar Listo tienes 2 segundos: levanta el borde de ARRIBA (el de la cámara) unos 45° y vuelve a bajarlo, como si el móvil asintiera.",
        "Lay it flat. After pressing Ready you have 2 seconds: lift the TOP edge (the camera one) about 45° and lower it again, as if the phone nodded.",
    ),
    ("cal.step5_title", "5 · Levanta el borde izquierdo", "5 · Lift the left edge"),
    (
        "cal.step5_text",
        "Plano otra vez. Al pulsar Listo tienes 2 segundos: levanta el lado IZQUIERDO unos 45° (se ladea hacia la derecha) y bájalo.",
        "Flat again. After pressing Ready you have 2 seconds: lift the LEFT side about 45° (it tilts to the right) and lower it.",
    ),
    ("cal.step6_title", "6 · Gira como un volante", "6 · Turn like a steering wheel"),
    (
        "cal.step6_text",
        "Plano sobre la mesa. Al pulsar Listo tienes 2 segundos: sin levantarlo, gíralo un cuarto de vuelta hacia la IZQUIERDA, como un volante.",
        "Flat on the table. After pressing Ready you have 2 seconds: without lifting it, turn it a quarter turn to the LEFT, like a steering wheel.",
    ),
    (
        "cal.no_gravity",
        "No veo la gravedad en el eje {0} (accel [{1} {2} {3}]). Repite la postura, quieto.",
        "I cannot see gravity on axis {0} (accel [{1} {2} {3}]). Repeat the pose, still.",
    ),
    (
        "cal.no_turn",
        "No veo un giro claro en el eje {0} (giro [{1}° {2}° {3}°]). Repite el gesto, más amplio y solo ese.",
        "I cannot see a clear turn on axis {0} (turn [{1}° {2}° {3}°]). Repeat the gesture, wider and only that one.",
    ),
    // --- enlace
    ("link.bad_addr", "Dirección no válida {0}:{1}: {2}", "Invalid address {0}:{1}: {2}"),
    ("link.bad_addr_short", "Dirección no válida {0}:{1}", "Invalid address {0}:{1}"),
    ("link.unreachable", "No llego a {0}:{1}: {2}", "Cannot reach {0}:{1}: {2}"),
    ("link.no_reply", "El PC no responde: {0}", "The PC is not responding: {0}"),
    ("link.unreadable", "Respuesta ilegible del PC", "Unreadable reply from the PC"),
    ("link.no_token", "El PC no devolvió el token (¿receptor antiguo? actualízalo)", "The PC did not return the token (old receiver? update it)"),
    ("link.rejected", "Rechazado", "Rejected"),
    ("link.unexpected", "Respuesta inesperada del PC", "Unexpected reply from the PC"),
    ("link.lost", "Se perdió la conexión con {0}", "Lost the connection to {0}"),
    ("link.unreachable_pc", "No llego a {0} ({1}:{2}): {3}", "Cannot reach {0} ({1}:{2}): {3}"),
    ("link.rejected_by_pc", "Rechazado por el PC", "Rejected by the PC"),
    // --- pantalla del GamePad
    ("scr.no_screen", "El PC no envía la pantalla", "The PC is not sending the screen"),
    ("scr.connecting", "Conectando la pantalla…", "Connecting the screen…"),
    ("scr.unreachable", "no llego a {0}:{1}: {2}", "cannot reach {0}:{1}: {2}"),
    // --- avisos locales
    ("notice.old_pc", "El PC necesita PepoMote 1.3 para Wii U", "The PC needs PepoMote 1.3 for Wii U"),
    ("notice.only_p1", "Solo el Jugador 1 cambia el modo", "Only Player 1 changes the mode"),
];

/// Fuentes con textos, para el test de completitud de `i18n`.
#[cfg(test)]
pub const SOURCES: &[&str] = &[
    include_str!("app.rs"),
    include_str!("link.rs"),
    include_str!("screen.rs"),
    include_str!("calib.rs"),
    include_str!("ui/controller.rs"),
    include_str!("ui/gamepad.rs"),
    include_str!("ui/nunchuk.rs"),
    include_str!("ui/keypad.rs"),
    include_str!("ui/text.rs"),
    include_str!("ui/layout_picker.rs"),
];
