//! Textos del móvil Linux que ve el usuario: (clave, español, inglés). El
//! idioma activo lo pone `i18n` (compartido con el receptor); `tr!("clave")`
//! devuelve el texto y `tr!("clave", a, b)` rellena `{0}`, `{1}`.

pub const TABLE: &[(&str, &str, &str)] = &[
    // --- común
    ("common.connecting", "Conectando…", "Connecting…"),
    ("common.reconnecting", "Reconectando…", "Reconnecting…"),
    ("common.no_connection", "Sin conexión", "No connection"),
    ("common.reconnect", "Reconectar", "Reconnect"),
    ("common.back", "Volver", "Back"),
    ("common.exit", "Salir", "Exit"),
    ("common.keyboard", "Teclado", "Keyboard"),
    ("common.mode_pointer", "Puntero", "Pointer"),
    ("common.mode_dolphin", "Dolphin", "Dolphin"),
    ("common.mode_cemu", "Wii U", "Wii U"),
    ("common.in_cemu", "En Cemu soy:", "In Cemu I am:"),
    ("common.gamepad", "GamePad", "GamePad"),
    ("common.pro", "Pro Controller", "Pro Controller"),
    ("common.wiimote", "Mando de Wii", "Wii Remote"),
    // --- inicio
    ("home.tagline", "Apunta. Haz clic. Juega.", "Point. Click. Play."),
    ("home.lang_switch", "Cambiar a {0}", "Switch to {0}"),
    ("home.connected", "Conectado a {0}", "Connected to {0}"),
    ("home.reconnecting", "Reconectando con {0}…", "Reconnecting to {0}…"),
    ("home.paired", "Emparejado con {0} · sin conexión", "Paired with {0} · no connection"),
    ("home.unpaired", "Sin emparejar: toca Conectar", "Not paired: tap Connect"),
    ("home.card_connect", "Conectar", "Connect"),
    ("home.card_connect_sub", "apunta y haz clic", "point and click"),
    ("home.card_pad", "Mando", "Controller"),
    ("home.card_pad_sub", "solo botones", "buttons only"),
    ("home.card_dolphin", "Dolphin", "Dolphin"),
    ("home.card_dolphin_sub", "Wiimote virtual", "virtual Wiimote"),
    ("home.card_nunchuk", "Nunchuk", "Nunchuk"),
    ("home.card_nunchuk_sub", "la otra mano", "the other hand"),
    ("home.card_wiiu", "Wii U", "Wii U"),
    ("home.card_wiiu_sub", "GamePad para Cemu", "GamePad for Cemu"),
    ("home.card_pair", "Emparejar", "Pair"),
    ("home.card_pair_sub", "otro PC / código", "another PC / code"),
    ("home.sensors", "Sensores: {0}", "Sensors: {0}"),
    ("home.no_sensors", "sin sensores: {0}", "no sensors: {0}"),
    ("home.calibrate", "Calibrar sensores", "Calibrate sensors"),
    (
        "home.calibrate_tip",
        "Si el puntero va al revés o a tirones: seis posturas guiadas y listo",
        "If the pointer goes backwards or jerks: six guided poses and done",
    ),
    ("home.theme", "Tema", "Theme"),
    ("home.theme_system", "Sistema", "System"),
    ("home.theme_light", "Claro", "Light"),
    ("home.theme_dark", "Oscuro", "Dark"),
    ("home.version", "v{0} · pv1 · Linux móvil", "v{0} · pv1 · Linux phone"),
    // --- emparejar
    ("pair.title", "Conectar", "Connect"),
    ("pair.title_again", "Vuelve a emparejar", "Pair again"),
    (
        "pair.subtitle",
        "Abre PepoMote en tu PC. Elige tu PC y teclea el código de 4 dígitos que hay bajo su QR.",
        "Open PepoMote on your PC. Pick your PC and type the 4-digit code under its QR.",
    ),
    ("pair.your_pcs", "Tus PCs", "Your PCs"),
    ("pair.current", " · actual", " · current"),
    ("pair.online", " · en la red", " · on the network"),
    ("pair.forget", "Olvidar", "Forget"),
    ("pair.scanning", "Buscando receptores en tu red…", "Looking for receivers on your network…"),
    (
        "pair.none",
        "Ningún receptor a la vista (¿misma Wi-Fi?). Puedes escribir la IP a mano.",
        "No receiver in sight (same Wi-Fi?). You can type the IP by hand.",
    ),
    ("pair.on_network", "En tu red:", "On your network:"),
    ("pair.manual_ip", "Escribir IP a mano", "Type the IP by hand"),
    ("pair.your_pc", "Tu PC", "Your PC"),
    (
        "pair.not_responding",
        "{0} no responde. Elige otro PC o teclea el código de otro.",
        "{0} is not responding. Pick another PC or type another one's code.",
    ),
    (
        "pair.re_pair",
        "{0} ya no reconoce este móvil: su emparejamiento ha cambiado (PepoMote reinstalado o restablecido en el PC). Elige tu PC y teclea el código nuevo que hay bajo su QR.",
        "{0} no longer recognises this phone: its pairing has changed (PepoMote reinstalled or reset on the PC). Pick your PC and type the new code under its QR.",
    ),
    ("manual.title", "IP del PC", "PC's IP"),
    ("manual.subtitle", "La que muestra el receptor bajo el QR (IP : puerto)", "The one the receiver shows under the QR (IP : port)"),
    ("code.title", "Código", "Code"),
    ("code.subtitle", "Los 4 dígitos bajo el QR de {0}", "The 4 digits under {0}'s QR"),
    ("code.pairing", "Emparejando…", "Pairing…"),
    // --- mando
    ("ctl.title_player", "{0} · Jugador {1}", "{0} · Player {1}"),
    ("ctl.wiiu_wiimote", "Wii U · Mando de Wii", "Wii U · Wii Remote"),
    ("ctl.pointer_p1", "Puntero: apunta el Jugador 1", "Pointer: Player 1 points"),
    (
        "ctl.pad_help",
        "Para juegos de Wii U que se juegan con el mando de Wii (Wii Sports Club, Wii Party U…)",
        "For Wii U games played with the Wii Remote (Wii Sports Club, Wii Party U…)",
    ),
    ("ctl.media_open", "Multimedia ▲", "Media ▲"),
    ("ctl.media_closed", "Multimedia ▼", "Media ▼"),
    // --- GamePad
    ("gp.rotate_left", "Giro ◀", "Turn ◀"),
    ("gp.rotate_right", "Giro ▶", "Turn ▶"),
    ("gp.title", "{0} · J{1} · {2}", "{0} · P{1} · {2}"),
    ("gp.screen_fps", " · pantalla · {0} fps", " · screen · {0} fps"),
    ("gp.tv_pad", "TV/Pad", "TV/Pad"),
    ("gp.blow", "Soplar", "Blow"),
    ("gp.veil_wiimote", "Ahora eres Mando de Wii", "You are now a Wii Remote"),
    ("gp.veil_switching", "Cambiando el PC a Wii U…", "Switching the PC to Wii U…"),
    ("gp.touch", "Pantalla táctil", "Touch screen"),
    // --- Nunchuk
    ("nk.line", "Nunchuk · Jugador {0} · {1}", "Nunchuk · Player {0} · {1}"),
    ("nk.old_pc", "El PC te ve como mando: actualiza el receptor", "The PC sees you as a controller: update the receiver"),
    (
        "nk.help",
        "En Wii U el Nunchuk solo funciona si el mando elige Mando de Wii",
        "On Wii U the Nunchuk only works if the controller picks Wii Remote",
    ),
    // --- teclado
    ("kb.space", "espacio", "space"),
    ("kb.title", "Teclado para Cemu", "Keyboard for Cemu"),
    (
        "kb.subtitle",
        "Lo que escribas va al teclado en pantalla del juego. El mando sigue funcionando.",
        "What you type goes to the game's on-screen keyboard. The controller keeps working.",
    ),
    ("kb.placeholder", "Escribe aquí…", "Type here…"),
    ("kb.delete", "Borrar", "Delete"),
    ("kb.write", "Escribir", "Type"),
    ("kb.accept", "Aceptar", "Accept"),
    (
        "kb.help",
        "Borrar quita una letra en Cemu · Escribir la teclea · Aceptar la teclea y confirma",
        "Delete removes a letter in Cemu · Type types it · Accept types it and confirms",
    ),
    ("kb.close", "Cerrar", "Close"),
    // --- calibración
    ("cal.title", "Calibrar sensores", "Calibrate sensors"),
    (
        "cal.subtitle",
        "Tres posturas quietas y tres gestos: así sé hacia dónde mira cada eje de tus sensores.",
        "Three still poses and three gestures: that is how I learn which way each sensor axis points.",
    ),
    ("cal.done", "Listo. Calibración guardada:", "Done. Calibration saved:"),
    ("cal.identity", "Todos los ejes ya venían bien.", "All axes were already right."),
    ("cal.inverted", "Los ejes marcados con - se invierten a partir de ahora.", "Axes marked with - are inverted from now on."),
    ("cal.step_of", "Paso {0} de {1}", "Step {0} of {1}"),
    ("cal.go", "¡Ya! Mueve", "Now! Move"),
    ("cal.measuring", "Midiendo", "Measuring"),
    ("cal.countdown", "{0}… {1} s", "{0}… {1} s"),
    ("cal.ready", "Listo", "Ready"),
    ("cal.waiting", "Esperando muestras del sensor…", "Waiting for sensor samples…"),
    ("cal.cancel", "Cancelar", "Cancel"),
    ("cal.clear", "Borrar calibración", "Clear calibration"),
    ("cal.open_err", "No puedo abrir los sensores para calibrar: {0}", "Cannot open the sensors to calibrate: {0}"),
    ("cal.step1_title", "1 · Plano boca arriba", "1 · Flat, face up"),
    (
        "cal.step1_text",
        "Deja el móvil plano sobre la mesa, con la pantalla hacia arriba, y pulsa Listo.",
        "Lay the phone flat on the table, screen up, and press Ready.",
    ),
    ("cal.step2_title", "2 · De pie", "2 · Standing"),
    (
        "cal.step2_text",
        "Ponlo de pie, apoyado en el borde de abajo (el del USB), con la pantalla hacia ti, como si lo estuvieras leyendo. Sujétalo quieto y pulsa Listo.",
        "Stand it on its bottom edge (the USB one), screen facing you, as if you were reading it. Hold it still and press Ready.",
    ),
    ("cal.step3_title", "3 · Sobre el lado izquierdo", "3 · On its left side"),
    (
        "cal.step3_text",
        "Túmbalo de canto sobre su lado IZQUIERDO, con la pantalla hacia ti: queda apaisado, con la cámara hacia tu izquierda. Quieto, y pulsa Listo.",
        "Lay it on its LEFT side, screen facing you: landscape, camera to your left. Still, and press Ready.",
    ),
    ("cal.step4_title", "4 · Levanta el borde superior", "4 · Lift the top edge"),
    (
        "cal.step4_text",
        "Déjalo plano. Al pulsar Listo tienes 2 segundos: levanta el borde de ARRIBA (el de la cámara) unos 45° y vuelve a bajarlo, como si el móvil asintiera.",
        "Lay it flat. After pressing Ready you have 2 seconds: lift the TOP edge (the camera one) about 45° and lower it again, as if the phone nodded.",
    ),
    ("cal.step5_title", "5 · Levanta el borde izquierdo", "5 · Lift the left edge"),
    (
        "cal.step5_text",
        "Plano otra vez. Al pulsar Listo tienes 2 segundos: levanta el lado IZQUIERDO unos 45° (se ladea hacia la derecha) y bájalo.",
        "Flat again. After pressing Ready you have 2 seconds: lift the LEFT side about 45° (it tilts to the right) and lower it.",
    ),
    ("cal.step6_title", "6 · Gira como un volante", "6 · Turn like a steering wheel"),
    (
        "cal.step6_text",
        "Plano sobre la mesa. Al pulsar Listo tienes 2 segundos: sin levantarlo, gíralo un cuarto de vuelta hacia la IZQUIERDA, como un volante.",
        "Flat on the table. After pressing Ready you have 2 seconds: without lifting it, turn it a quarter turn to the LEFT, like a steering wheel.",
    ),
    (
        "cal.no_gravity",
        "No veo la gravedad en el eje {0} (accel [{1} {2} {3}]). Repite la postura, quieto.",
        "I cannot see gravity on axis {0} (accel [{1} {2} {3}]). Repeat the pose, still.",
    ),
    (
        "cal.no_turn",
        "No veo un giro claro en el eje {0} (giro [{1}° {2}° {3}°]). Repite el gesto, más amplio y solo ese.",
        "I cannot see a clear turn on axis {0} (turn [{1}° {2}° {3}°]). Repeat the gesture, wider and only that one.",
    ),
    // --- enlace
    ("link.bad_addr", "Dirección no válida {0}:{1}: {2}", "Invalid address {0}:{1}: {2}"),
    ("link.bad_addr_short", "Dirección no válida {0}:{1}", "Invalid address {0}:{1}"),
    ("link.unreachable", "No llego a {0}:{1}: {2}", "Cannot reach {0}:{1}: {2}"),
    ("link.no_reply", "El PC no responde: {0}", "The PC is not responding: {0}"),
    ("link.unreadable", "Respuesta ilegible del PC", "Unreadable reply from the PC"),
    ("link.no_token", "El PC no devolvió el token (¿receptor antiguo? actualízalo)", "The PC did not return the token (old receiver? update it)"),
    ("link.rejected", "Rechazado", "Rejected"),
    ("link.unexpected", "Respuesta inesperada del PC", "Unexpected reply from the PC"),
    ("link.lost", "Se perdió la conexión con {0}", "Lost the connection to {0}"),
    ("link.unreachable_pc", "No llego a {0} ({1}:{2}): {3}", "Cannot reach {0} ({1}:{2}): {3}"),
    ("link.rejected_by_pc", "Rechazado por el PC", "Rejected by the PC"),
    // --- pantalla del GamePad
    ("scr.no_screen", "El PC no envía la pantalla", "The PC is not sending the screen"),
    ("scr.connecting", "Conectando la pantalla…", "Connecting the screen…"),
    ("scr.unreachable", "no llego a {0}:{1}: {2}", "cannot reach {0}:{1}: {2}"),
    // --- avisos locales
    ("notice.old_pc", "El PC necesita PepoMote 1.3 para Wii U", "The PC needs PepoMote 1.3 for Wii U"),
    ("notice.only_p1", "Solo el Jugador 1 cambia el modo", "Only Player 1 changes the mode"),
];

/// Fuentes con textos, para el test de completitud de `i18n`.
#[cfg(test)]
pub const SOURCES: &[&str] = &[
    include_str!("app.rs"),
    include_str!("link.rs"),
    include_str!("screen.rs"),
    include_str!("calib.rs"),
    include_str!("ui/controller.rs"),
    include_str!("ui/gamepad.rs"),
    include_str!("ui/nunchuk.rs"),
    include_str!("ui/keypad.rs"),
    include_str!("ui/text.rs"),
];
